# Generated by Django 5.1 on 2024-09-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Productos',
        ),
    ]
